name: stable diffusion webui docker
on:
  workflow_dispatch:
    inputs:
      docker_username:
        description: 'docker user name'
        required: true
        default: ''
      docker_password:
        description: 'docker user password'
        required: true
        default: ''
      version:
        description: 'image version'
        required: true
        default: ''
    branches:
      - master
    paths:
      - docker-compose.yml
      - services

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      -
        name: Checkout
        uses: actions/checkout@master

      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.event.inputs.docker_username }}
          password: ${{ github.event.inputs.docker_password }}
          
      - 
        name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: AUTOMATIC1111
          file: AUTOMATIC1111/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ github.event.inputs.docker_username }}/stable-diffusion-webui:latest
            ${{ github.event.inputs.docker_username }}stable-diffusion-webui:${{ github.event.inputs.version }}
